# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import api_pb2 as proto_dot_api__pb2


class electConsumePostStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.electConsume = channel.unary_unary(
                '/billManagerAPI.electConsumePost/electConsume',
                request_serializer=proto_dot_api__pb2.electConsumeData.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class electConsumePostServicer(object):
    """Missing associated documentation comment in .proto file."""

    def electConsume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_electConsumePostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'electConsume': grpc.unary_unary_rpc_method_handler(
                    servicer.electConsume,
                    request_deserializer=proto_dot_api__pb2.electConsumeData.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'billManagerAPI.electConsumePost', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class electConsumePost(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def electConsume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/billManagerAPI.electConsumePost/electConsume',
            proto_dot_api__pb2.electConsumeData.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class electConsumeGetStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.electConsume = channel.unary_unary(
                '/billManagerAPI.electConsumeGet/electConsume',
                request_serializer=proto_dot_api__pb2.Date.SerializeToString,
                response_deserializer=proto_dot_api__pb2.onedayElectConsume.FromString,
                )


class electConsumeGetServicer(object):
    """Missing associated documentation comment in .proto file."""

    def electConsume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_electConsumeGetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'electConsume': grpc.unary_unary_rpc_method_handler(
                    servicer.electConsume,
                    request_deserializer=proto_dot_api__pb2.Date.FromString,
                    response_serializer=proto_dot_api__pb2.onedayElectConsume.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'billManagerAPI.electConsumeGet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class electConsumeGet(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def electConsume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/billManagerAPI.electConsumeGet/electConsume',
            proto_dot_api__pb2.Date.SerializeToString,
            proto_dot_api__pb2.onedayElectConsume.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
