version: '3'
services:

  api:
    image: azuki774/bill-manager-api
    container_name: bill-manager-api
    restart: always

  db:
    image: azuki774/bill-manager-db
    container_name: bill-manager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : billmanager
      MYSQL_HOST: bill-manager-db
      MYSQL_DATABASE: BILLMANAGER
      TZ: Asia/Tokyo
      LANG: C.UTF-8

  fetcher:
    image: azuki774/bill-manager-fetcher
    container_name: bill-manager-fetcher
    restart: always
    env_file:
    - fetcher-token.env

  mawinter-client:
    image: azuki774/bill-manager-mawinter
    container_name: bill-manager-mawinter
    restart: always

  twitter-client:
    image: azuki774/bill-manager-twitter
    container_name: bill-manager-twitter
    restart: always
    env_file:
    - tw-token.env
    environment:
    - twitter_stub=1 # 0 .. send to Twitter, 1 .. for development (not send actually)
