apiVersion: batch/v1
kind: CronJob
metadata:
  name: bill-manager-twitter
spec:
  schedule: "30 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: ghcr.io/azuki774/bill-manager-twitter:latest
            name: bill-manager-twitter
            env:
            - name: twitter_stub
              value: "0"
            - name: consumer_key
              valueFrom:
                secretKeyRef:
                  name: bill-manager-twitter
                  key: consumer_key
            - name: consumer_secret
              valueFrom:
                secretKeyRef:
                  name: bill-manager-twitter
                  key: consumer_secret
            - name: access_token
              valueFrom:
                secretKeyRef:
                  name: bill-manager-twitter
                  key: access_token
            - name: access_token_secret
              valueFrom:
                secretKeyRef:
                  name: bill-manager-twitter
                  key: access_token_secret
          restartPolicy: Never
