version: '3'
services:
  db:
    image: mariadb:10.9
    container_name: bill-manager-db
    restart: always
    container_name: bill-manager-db
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=billmanager
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo

  bill-manager-api:
    image: bill-manager-api
    container_name: bill-manager-api
    ports:
      - "8080:80"

  # bill-manager-water:
  #   image: bill-manager-water
  #   container_name: bill-manager-water
  #   volumes:
  #     - ./:/root/fetcher/water/

  # bill-manager-gas:
  #   image: bill-manager-gas
  #   container_name: bill-manager-gas
  #   volumes:
  #     - ./:/root/fetcher/

  # mawinter-client:
  #   image: bill-manager-mawinter
  #   container_name: bill-manager-mawinter
  #   restart: always

  # twitter-client:
  #   image: bill-manager-twitter
  #   container_name: bill-manager-twitter
  #   env_file:
  #     - tw-token.env
  #   environment:
  #     only_print_debug: 1
  #     db_host: bill-manager-db
  #     db_user: root
  #     db_pass: password
