version: '3'
services:
  db:
    image: mariadb:10.9
    container_name: bill-manager-db
    restart: always
    container_name: bill-manager-db
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=billmanager
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo

  mawinter-client:
    image: bill-manager-mawinter
    container_name: bill-manager-mawinter
    restart: always

  twitter-client:
    image: bill-manager-twitter
    container_name: bill-manager-twitter
    restart: always
    env_file:
      - tw-token.env
    environment:
      twitter_stub: 1 # 0 .. send to Twitter, 1 .. for development (not send actually)
      start_wait: 20
