version: '3'
services:
  maw-db:
    image: ghcr.io/azuki774/mawinter-db:latest
    restart: always
    container_name: mawinter-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mawinter
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - TZ=Asia/Tokyo
    volumes:
      - ../build/mawinter-initdb.d:/docker-entrypoint-initdb.d
  maw-api:
    image: ghcr.io/azuki774/mawinter-api:latest
    container_name: mawinter-api
    ports:
      - "8888:8080"
    environment:
      - MYSQL_DATABASE=mawinter
      - BASIC_AUTH_USERNAME=test
      - BASIC_AUTH_PASSWORD=test

