apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-manager-api
spec:
  selector:
    matchLabels:
      app: bill-manager-api
  template:
    metadata:
      labels:
        app: bill-manager-api
    spec:
      resource:
      containers:
      - name: bill-manager-api
        image: ghcr.io/azuki774/bill-manager-api:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bill-manager-api
spec:
  selector:
    app: bill-manager-api
  ports:
  - port: 9999
  type: NodePort
