apiVersion: batch/v1
kind: Job
metadata:
  name: bill-manager-fetcher-test
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/azuki774/bill-manager-fetcher:develop
        name: bill-manager-fetcher-test
        env:
        - name: fetcher_stub
          value: "0"
        - name: remix_id
          valueFrom:
            secretKeyRef:
              name: bill-manager-fetcher-remix
              key: remix_id
        - name: remix_pass
          valueFrom:
            secretKeyRef:
              name: bill-manager-fetcher-remix
              key: remix_pass
      restartPolicy: Never
