# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/api.proto',
  package='billManagerAPI',
  syntax='proto3',
  serialized_options=b'Z1github.com/azuki774/bill-manager/internal/grpcapi',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fproto/api.proto\x12\x0e\x62illManagerAPI\x1a\x1bgoogle/protobuf/empty.proto\"q\n\x12OnedayElectConsume\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.billManagerAPI.DateStruct\x12\x0f\n\x07\x64\x61ytime\x18\x02 \x01(\x03\x12\x11\n\tnighttime\x18\x03 \x01(\x03\x12\r\n\x05total\x18\x04 \x01(\x03\"6\n\nDateStruct\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\x32\xb8\x01\n\x13\x45lectConsumeService\x12N\n\x10\x45lectConsumePost\x12\".billManagerAPI.OnedayElectConsume\x1a\x16.google.protobuf.Empty\x12Q\n\x0f\x45lectConsumeGet\x12\x1a.billManagerAPI.DateStruct\x1a\".billManagerAPI.OnedayElectConsumeB3Z1github.com/azuki774/bill-manager/internal/grpcapib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ONEDAYELECTCONSUME = _descriptor.Descriptor(
  name='OnedayElectConsume',
  full_name='billManagerAPI.OnedayElectConsume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='billManagerAPI.OnedayElectConsume.date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='daytime', full_name='billManagerAPI.OnedayElectConsume.daytime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nighttime', full_name='billManagerAPI.OnedayElectConsume.nighttime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='billManagerAPI.OnedayElectConsume.total', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=177,
)


_DATESTRUCT = _descriptor.Descriptor(
  name='DateStruct',
  full_name='billManagerAPI.DateStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='billManagerAPI.DateStruct.year', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='month', full_name='billManagerAPI.DateStruct.month', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='day', full_name='billManagerAPI.DateStruct.day', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=233,
)

_ONEDAYELECTCONSUME.fields_by_name['date'].message_type = _DATESTRUCT
DESCRIPTOR.message_types_by_name['OnedayElectConsume'] = _ONEDAYELECTCONSUME
DESCRIPTOR.message_types_by_name['DateStruct'] = _DATESTRUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OnedayElectConsume = _reflection.GeneratedProtocolMessageType('OnedayElectConsume', (_message.Message,), {
  'DESCRIPTOR' : _ONEDAYELECTCONSUME,
  '__module__' : 'proto.api_pb2'
  # @@protoc_insertion_point(class_scope:billManagerAPI.OnedayElectConsume)
  })
_sym_db.RegisterMessage(OnedayElectConsume)

DateStruct = _reflection.GeneratedProtocolMessageType('DateStruct', (_message.Message,), {
  'DESCRIPTOR' : _DATESTRUCT,
  '__module__' : 'proto.api_pb2'
  # @@protoc_insertion_point(class_scope:billManagerAPI.DateStruct)
  })
_sym_db.RegisterMessage(DateStruct)


DESCRIPTOR._options = None

_ELECTCONSUMESERVICE = _descriptor.ServiceDescriptor(
  name='ElectConsumeService',
  full_name='billManagerAPI.ElectConsumeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=236,
  serialized_end=420,
  methods=[
  _descriptor.MethodDescriptor(
    name='ElectConsumePost',
    full_name='billManagerAPI.ElectConsumeService.ElectConsumePost',
    index=0,
    containing_service=None,
    input_type=_ONEDAYELECTCONSUME,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ElectConsumeGet',
    full_name='billManagerAPI.ElectConsumeService.ElectConsumeGet',
    index=1,
    containing_service=None,
    input_type=_DATESTRUCT,
    output_type=_ONEDAYELECTCONSUME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ELECTCONSUMESERVICE)

DESCRIPTOR.services_by_name['ElectConsumeService'] = _ELECTCONSUMESERVICE

# @@protoc_insertion_point(module_scope)
