# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/api.proto\x12\x0e\x62illManagerAPI\x1a\x1bgoogle/protobuf/empty.proto\"q\n\x12OnedayElectConsume\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.billManagerAPI.DateStruct\x12\x0f\n\x07\x64\x61ytime\x18\x02 \x01(\x03\x12\x11\n\tnighttime\x18\x03 \x01(\x03\x12\r\n\x05total\x18\x04 \x01(\x03\"6\n\nDateStruct\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\x32\xb8\x01\n\x13\x45lectConsumeService\x12N\n\x10\x45lectConsumePost\x12\".billManagerAPI.OnedayElectConsume\x1a\x16.google.protobuf.Empty\x12Q\n\x0f\x45lectConsumeGet\x12\x1a.billManagerAPI.DateStruct\x1a\".billManagerAPI.OnedayElectConsumeB3Z1github.com/azuki774/bill-manager/internal/grpcapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/azuki774/bill-manager/internal/grpcapi'
  _ONEDAYELECTCONSUME._serialized_start=64
  _ONEDAYELECTCONSUME._serialized_end=177
  _DATESTRUCT._serialized_start=179
  _DATESTRUCT._serialized_end=233
  _ELECTCONSUMESERVICE._serialized_start=236
  _ELECTCONSUMESERVICE._serialized_end=420
# @@protoc_insertion_point(module_scope)
