name: Build and Publish Docker

on:
  push:
    tags:
      - v*

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: test
      run: go test -v ./...

  build_and_push_api:
    runs-on: ubuntu-latest
    needs: gotest
    env:
      IMAGE_NAME: bill-manager-api
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/azuki774/bill-manager-api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: build
        run: make build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfile-api
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  build_and_push_db:
    runs-on: ubuntu-latest
    needs: gotest
    env:
      IMAGE_NAME: bill-manager-db
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/azuki774/bill-manager-db
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: build
        run: make build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build and push DB
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfile-db
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  build_and_push_mawinter:
    runs-on: ubuntu-latest
    needs: gotest
    env:
      IMAGE_NAME: bill-manager-mawinter
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/azuki774/bill-manager-mawinter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest

  build_and_push_fetcher:
    runs-on: ubuntu-latest
    needs: gotest
    env:
      IMAGE_NAME: bill-manager-fetcher
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/azuki774/bill-manager-fetcher
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: build
        run: make build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build and push fetcher
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfile-fetcher
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  build_and_push_twitter:
    runs-on: ubuntu-latest
    needs: gotest
    env:
      IMAGE_NAME: bill-manager-twitter
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/azuki774/bill-manager-twitter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: build
        run: make build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build and push twitter-client
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfile-twitter
          push: true
          tags: ${{ steps.meta.outputs.tags }}
