name: Build and Publish Docker

on:
  pull_request:
    branches:
    - '**' 

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: test
      run: go test -v ./...

  build_and_push:
    runs-on: ubuntu-latest
    needs: gotest
    env:
      IMAGE_NAME: bill-manager-api
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: build
        run: make build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfile-api
          push: true
          tags: ghcr.io/azuki774/bill-manager-api:develop

      - name: Build and push DB
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfile-db
          push: true
          tags: ghcr.io/azuki774/bill-manager-db:develop

      - name: Build and push fetcher
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfile-fetcher
          push: true
          tags: ghcr.io/azuki774/bill-manager-fetcher:develop

      - name: Build and push twclient
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfile-twitter
          push: true
          tags: ghcr.io/azuki774/bill-manager-twitter:develop
